/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author DELL
 */

public class ControlPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PuntoVenta
     */
    public ControlPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmiVenta = new javax.swing.JMenu();
        jmiNuevaVenta = new javax.swing.JMenuItem();
        jmiConsultarVenta = new javax.swing.JMenuItem();
        jmiProducto = new javax.swing.JMenu();
        jmiNuevoProducto = new javax.swing.JMenuItem();
        jmiEliminarProducto = new javax.swing.JMenuItem();
        jmiProductosVenta = new javax.swing.JMenuItem();
        jmiProveedor = new javax.swing.JMenu();
        jmiNuevoProveedor = new javax.swing.JMenuItem();
        jmiEliminarProveedor = new javax.swing.JMenuItem();
        jmiConsultarProveedor = new javax.swing.JMenuItem();
        jmiAlmacen = new javax.swing.JMenu();
        jmiAlmacenar = new javax.swing.JMenuItem();
        jmiConsultarProducto = new javax.swing.JMenuItem();
        jmiEmpleado = new javax.swing.JMenu();
        jmiReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 199, 163));

        jButton2.setBackground(new java.awt.Color(169, 0, 188));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 200));

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setBorder(null);

        jmiVenta.setBorder(null);
        jmiVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Venta.png"))); // NOI18N
        jmiVenta.setText("Ventas");

        jmiNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nueva.png"))); // NOI18N
        jmiNuevaVenta.setText("Nueva Venta");
        jmiNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaVentaActionPerformed(evt);
            }
        });
        jmiVenta.add(jmiNuevaVenta);

        jmiConsultarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConsultarCorte.png"))); // NOI18N
        jmiConsultarVenta.setText("ConsultarVentas");
        jmiConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarVentaActionPerformed(evt);
            }
        });
        jmiVenta.add(jmiConsultarVenta);

        jMenuBar2.add(jmiVenta);

        jmiProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Producto.png"))); // NOI18N
        jmiProducto.setText("Producto");

        jmiNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevaVenta.png"))); // NOI18N
        jmiNuevoProducto.setText("Nuevo");
        jmiNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoProductoActionPerformed(evt);
            }
        });
        jmiProducto.add(jmiNuevoProducto);

        jmiEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        jmiEliminarProducto.setText("Eliminar");
        jmiEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarProductoActionPerformed(evt);
            }
        });
        jmiProducto.add(jmiEliminarProducto);

        jmiProductosVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Almacen.png"))); // NOI18N
        jmiProductosVenta.setText("Productos Venta");
        jmiProductosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosVentaActionPerformed(evt);
            }
        });
        jmiProducto.add(jmiProductosVenta);

        jMenuBar2.add(jmiProducto);

        jmiProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N
        jmiProveedor.setText("Proveedores");

        jmiNuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistrarProveedor.png"))); // NOI18N
        jmiNuevoProveedor.setText("Registrar Proveedor");
        jmiNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoProveedorActionPerformed(evt);
            }
        });
        jmiProveedor.add(jmiNuevoProveedor);

        jmiEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EliminarProveedor.png"))); // NOI18N
        jmiEliminarProveedor.setText("Eliminar Proveedor");
        jmiEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarProveedorActionPerformed(evt);
            }
        });
        jmiProveedor.add(jmiEliminarProveedor);

        jmiConsultarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConsultarProveedor.png"))); // NOI18N
        jmiConsultarProveedor.setText("Consultar Proveedores");
        jmiConsultarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarProveedorActionPerformed(evt);
            }
        });
        jmiProveedor.add(jmiConsultarProveedor);

        jMenuBar2.add(jmiProveedor);

        jmiAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Almacen.png"))); // NOI18N
        jmiAlmacen.setText("Almacen");

        jmiAlmacenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        jmiAlmacenar.setText("Almacenar");
        jmiAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlmacenarActionPerformed(evt);
            }
        });
        jmiAlmacen.add(jmiAlmacenar);

        jmiConsultarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ConsultarProducto.png"))); // NOI18N
        jmiConsultarProducto.setText("Consultar Almacen");
        jmiConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarProductoActionPerformed(evt);
            }
        });
        jmiAlmacen.add(jmiConsultarProducto);

        jMenuBar2.add(jmiAlmacen);

        jmiEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nota.png"))); // NOI18N
        jmiEmpleado.setText("Reportes");

        jmiReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Impresora.png"))); // NOI18N
        jmiReportes.setText("Imprimir");
        jmiReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReportesActionPerformed(evt);
            }
        });
        jmiEmpleado.add(jmiReportes);

        jMenuBar2.add(jmiEmpleado);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       Login lo=new Login();
        lo.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jmiNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaVentaActionPerformed
        // TODO add your handling code here:
        PuntodeVenta ptv=new PuntodeVenta();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiNuevaVentaActionPerformed

    private void jmiNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoProductoActionPerformed
        // TODO add your handling code here:
        ProductoNuevo ptv=new ProductoNuevo();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiNuevoProductoActionPerformed

    private void jmiEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarProductoActionPerformed
        // TODO add your handling code here:
        EliminarProducto ptv=new EliminarProducto();
       ptv.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jmiEliminarProductoActionPerformed

    private void jmiNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoProveedorActionPerformed
        // TODO add your handling code here:
       RegistrarProveedor ptv=new RegistrarProveedor();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiNuevoProveedorActionPerformed

    private void jmiEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarProveedorActionPerformed
        // TODO add your handling code here:
        EliminarProveedor ptv=new EliminarProveedor();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiEliminarProveedorActionPerformed

    private void jmiConsultarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarProveedorActionPerformed
        // TODO add your handling code here:
        ConsultarProveedor ptv=new ConsultarProveedor();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiConsultarProveedorActionPerformed

    private void jmiConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarProductoActionPerformed
        // TODO add your handling code here:
        ConsultarAlmacen ptv=new ConsultarAlmacen();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiConsultarProductoActionPerformed

    private void jmiConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarVentaActionPerformed
        // TODO add your handling code here:
        ConsultarVentas ptv=new ConsultarVentas();
        ptv.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jmiConsultarVentaActionPerformed

    private void jmiAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlmacenarActionPerformed
        // TODO add your handling code here:
        Almacenar ptv= new Almacenar();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiAlmacenarActionPerformed

    private void jmiProductosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosVentaActionPerformed
        // TODO add your handling code here:
        ProductosVentas ptv= new ProductosVentas();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiProductosVentaActionPerformed

    private void jmiReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReportesActionPerformed
        // TODO add your handling code here:
       ImprimirReportes ptv=new ImprimirReportes();
        ptv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmiAlmacen;
    private javax.swing.JMenuItem jmiAlmacenar;
    private javax.swing.JMenuItem jmiConsultarProducto;
    private javax.swing.JMenuItem jmiConsultarProveedor;
    private javax.swing.JMenuItem jmiConsultarVenta;
    private javax.swing.JMenuItem jmiEliminarProducto;
    private javax.swing.JMenuItem jmiEliminarProveedor;
    private javax.swing.JMenu jmiEmpleado;
    private javax.swing.JMenuItem jmiNuevaVenta;
    private javax.swing.JMenuItem jmiNuevoProducto;
    private javax.swing.JMenuItem jmiNuevoProveedor;
    private javax.swing.JMenu jmiProducto;
    private javax.swing.JMenuItem jmiProductosVenta;
    private javax.swing.JMenu jmiProveedor;
    private javax.swing.JMenuItem jmiReportes;
    private javax.swing.JMenu jmiVenta;
    // End of variables declaration//GEN-END:variables
}
